export const CREATE_SUBSCRIBER_REQUEST = "CREATE_SUBSCRIBER_REQUEST";
export const CREATE_SUBSCRIBER_SUCCESS = "CREATE_SUBSCRIBER_SUCCESS";
export const CREATE_SUBSCRIBER_FAIL = "CREATE_SUBSCRIBER_FAIL";
