export const PAYMENT_VERIFICATION_REQUEST = "PAYMENT_VERIFICATION_REQUEST";
export const PAYMENT_VERIFICATION_SUCCESS = "PAYMENT_VERIFICATION_SUCCESS";
export const PAYMENT_VERIFICATION_FAIL = "PAYMENT_VERIFICATION_FAIL";

export const MAKE_ORDER_ISPAID_REQUEST = "MAKE_ORDER_ISPAID_REQUEST";
export const MAKE_ORDER_ISPAID_SUCCESS = "MAKE_ORDER_ISPAID_SUCCESS";
export const MAKE_ORDER_ISPAID_FAIL = "MAKE_ORDER_ISPAID_FAIL";
