export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const CATEGORY_PRODUCTS_REQUEST = "CATEGORY_PRODUCTS_REQUEST";
export const CATEGORY_PRODUCTS_SUCCESS = "CATEGORY_PRODUCTS_SUCCESS";
export const CATEGORY_PRODUCTS_FAIL = "CATEGORY_PRODUCTS_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRICE_RANGE_REQUEST = "PRICE_RANGE_REQUEST";
export const PRICE_RANGE_SUCCESS = "PRICE_RANGE_SUCCESS";
export const PRICE_RANGE_FAIL = "PRICE_RANGE_FAIL";
